tests/abstract.py, tests/test_tracking.py, tests/util.py
Add software tests from MLflow's `tests.store.tracking.test_sqlalchemy_store`, without modifications. GH-10 will make them work.
=> Add software tests from MLflow

CHANGES.md, README.md, docs/backlog.md, mlflow_cratedb/cli.py, mlflow_cratedb/patch/mlflow/__init__.py, mlflow_cratedb/patch/mlflow/db_utils.py, mlflow_cratedb/patch/sqlalchemy.py, pyproject.toml, tests/conftest.py, tests/test_adapter.py, tests/test_cli.py, tests/test_mlflow.py
A few more improvements on different ends.
- Add patch for SQLAlchemy Inspector's `get_table_names` again. Contrary to the latest assessment, we still need it, see below.
- CLI: Add `mlflow-cratedb cratedb --version` command
- Project: Add `versioningit`, for effortless versioning
- Tests: Provide fixture `testdrive_engine` for the whole test suite
- Reorder CrateDB SQLAlchemy Dialect polyfills
- Update documentation
=> This and that

CHANGES.md, README.md, docs/container.md
On the 0.1.0 release, I forgot to correctly state `pip install --upgrade 'mlflow-cratedb[examples]'` in the README.
While already editing the documentation, and verifying that all steps work which have been written down in [docs/container.md](https://github.com/crate-workbench/mlflow-cratedb/blob/main/docs/container.md), I've improved it a bit more to be a coherent and self-contained walkthrough.
=> Last minute updates to the documentation

.gitignore, mlflow_cratedb/adapter/ddl/cratedb.sql
At least it makes the tab load and models can be created.
Fixes #17.
=> Add a few missing columns to make the Models tab load in the UI

CHANGES.md, examples/tracking_merlion.py
Based on @seut's suggestion at https://github.com/crate-workbench/mlflow-cratedb/pull/13#discussion_r1328668916. Thanks.
=> Improve `table_exists()` to use `CURRENT_SCHEMA` in `example_merlion.py`

CHANGES.md, mlflow_cratedb/patch/crate_python.py, pyproject.toml
Now uses the server-side `now()` function to patch column models using the "autoincrement" property, as suggested by @seut at https://github.com/crate/crate-python/issues/575#issuecomment-1723030490. Thanks!
=> SQLAlchemy: Use server-side `now()` function for "autoincrement" columns

CHANGES.md, README.md, docs/backlog.md, docs/container.md, docs/handbook.md, tests/test_adapter.py
FYI. Just a few documentation updates, partly based on your observations and reports - thanks again!
_Please don't hesitate to submit suggestions even retroactively after merging this patch. I will certainly take them into consideration._
/cc @ckurze
=> Update and improve documentation

CHANGES.md, mlflow_cratedb/patch/mlflow/model.py, tests/test_tracking_issues.py
Fixes an issue reported by @andnig - thanks!
- GH-46
@andnig: Thank you very much for the excellent preparation. You absolutely nailed the issue, including the right solution to the problem. Just the reproduction code, i.e. calling `log_model()` twice, could have been shorter, as you can see on behalf of the test case added here. It explicitly exercises the problem, and failed in the same way as you described at GH-46.
/cc @hammerhead, @ckurze
=> Fix uniqueness constraint with `SqlRegisteredModel.name`

.github/workflows/main.yml, .github/workflows/oci-server.yml, CHANGES.md, release/oci-runtime/Dockerfile, release/oci-server/Dockerfile
A few packages in the ML arena, like PyCaret, are apparently not ready for Python 3.11 yet.
@andnig has been tripped by this when trying to bring in an example about MLflow and PyCaret. It does not support Python 3.11 yet.
- GH-45
- https://github.com/pycaret/pycaret/pull/3756
It does not mean that the software will stop working on Python 3.11. It is only that we test Python 3.10 by default, and also build and ship the OCI images with Python 3.10 now, for better compatibility. I don't want to open the box of running a test matrix now, and would like to follow the suggestion by @andnig without further ado.
/cc @hammerhead, @ckurze
=> Downgrade to Python 3.10

CHANGES.md, mlflow_cratedb/adapter/ddl/cratedb.sql, pyproject.toml, tests/test_tracking.py
MLflow 2.8.0 was released three days ago.
https://github.com/mlflow/mlflow/releases/tag/v2.8.0
- GH-50
/cc @ckurze
=> Update to MLflow 2.8.0

CHANGES.md, mlflow_cratedb/patch/mlflow/model.py
Just a minor followup to GH-46.
The first CI run on this patch experienced an interesting fluke with CrateDB. We added a report at GH-53.
=> Fix uniqueness constraint with `.auth.db.models.SqlUser.username`

.gitignore, examples/tracking_pycaret.py, pyproject.toml, tests/test_examples.py
Provides an example for how to use pycaret to automatically benchmark, select and register a timeseries forecasting model.
Uses sales forecasting as example data.
Based on the canonical example track_merlion.py from @amotl .
Requires MLFLOW_TRACKING_URI to be set, as the example attempts to register the final model with MLflow. This does not work, if only file-based tracking is available.
=> add pycaret example and tests

CHANGES.md
The recent update to MLflow 2.8 needed an admonition to the changelog file about a new database column.
- GH-51
=> [docs] Notice about new `mlflow.model_versions.storage_location` column

CHANGES.md, mlflow_cratedb/patch/mlflow/model.py, pyproject.toml
GH-46 and GH-52 reported and fixed missing uniqueness constraints on the SQLAlchemy data model. This patch adds two more, based on recent improvements from https://github.com/crate-workbench/cratedb-toolkit/pull/70.
- SqlExperimentPermission: "experiment_id", "user_id"
- SqlRegisteredModelPermission: "name", "user_id"
/cc @hlcianfagna
=> Fix two more uniqueness constraints in SQLAlchemy data model

release/oci-runtime/Dockerfile, release/oci-server/Dockerfile
Now that we need `gcc` to satisfy the `psutil` dependency of MLflow, we uninstall it right away. In order that this makes sense, all commands (install/uninstall) need to be done in one run.
=> Optimize OCI image sizes

.github/workflows/main.yml, examples/tracking_merlion.py, examples/tracking_pycaret.py, pyproject.toml
Within the example programs, use `REFRESH TABLE ...` to synchronize CrateDB write operations before advancing to subsequent operations. Fixes GH-49.
Two more maintenance commits, nothing special.
=> Examples: Use `refresh_table` to synchronize CrateDB write operations

.github/workflows/oci-runtime.yml, .github/workflows/oci-server.yml
This reverts commit a1356ec72d692ddd479db8addabc8d4158c0ae02. It means we are not always building OCI images on each PR, because it is a rather heavy process.
=> Revert "CI: Build OCI images on PRs again"

.github/workflows/main.yml
This supports better discovering eventual regressions at CrateDB, and also adds additional churn to the repository, in order to detect other anomalies.
=> CI: Run integration tests each night

.github/workflows/main.yml
This may help in situations where the integration tests are heavy on
memory use, and where we observed flaky behaviour on CI.
According to GitHub's documentation, standard runners offer 16 GB of
RAM, so dedicating 4 GB to CrateDB will not blow up the main memory.
-- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
- GH-53
=> CI: Increase heap memory size for CrateDB to 4 GB

.github/workflows/main.yml
- GH-97
> Tokenless uploading is unsupported. However, PRs made from forks to
> the upstream public repos will support tokenless (e.g. contributors to
> OS projects do not need the upstream repo's Codecov token). This doc
> shows instructions on how to add the Codecov token.
>
> -- https://docs.codecov.com/docs/adding-the-codecov-token#github-actions
- https://github.com/panodata/aika/pull/55
=> CI: Update to codecov-action@v4

mlflow_cratedb/adapter/ddl/cratedb.sql, pyproject.toml, tests/test_examples.py, tests/test_tracking.py
Updating to MLflow 2.11 does not work without further ado.
- GH-121
Minor adjustments have been required to satisfy the test cases.
- GH-125
=> Update MLflow from 2.10.2 to 2.11.3

CHANGES.md, README.md, pyproject.toml
- Fix incompatibility with Python 3.11.9 by updating to cratedb-toolkit 0.0.10.
See also https://github.com/pycaret/pycaret/issues/3960#issuecomment-2045881422.
- Chore: Update Ruff configuration to match more recent versions.
- Update README.
=> Fix incompatibility with Python 3.11.9 and Dask

CHANGES.md, docs/backlog.md, mlflow_cratedb/patch/mlflow/model.py, mlflow_cratedb/patch/sqlalchemy.py, pyproject.toml
In order to trim dependencies, this patch validates a few details without installing the [cratedb-toolkit](https://github.com/crate-workbench/cratedb-toolkit) package, or otherwise depending on it. Instead, it uses the new [sqlalchemy-cratedb](https://github.com/crate/sqlalchemy-cratedb) package.
- https://github.com/crate/cratedb-examples/pull/498
=> Use SQLAlchemy patches and polyfills from `sqlalchemy-cratedb`

.github/workflows/oci-runtime.yml, .github/workflows/oci-server.yml
OCI builds on ARM started failing the other day.
```
131.0 Processing triggers for libc-bin (2.31-13+deb11u11) ...
131.1 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
131.4 Segmentation fault (core dumped)
```
- https://github.com/crate/mlflow-cratedb/issues/208
=> OCI: Fix segfaults on ARM builds
